In [1]:
from MSTOkG.MSTOOpt import *

In [2]:
# choose your element
element = 'LiH'
# get the default molecule in your basis
mol = moldict('sto-2g')[element]

In [3]:
moldict('sto-2g')

{'H': <pyscf.gto.mole.Mole at 0x128937b30>,
 'He': <pyscf.gto.mole.Mole at 0x127bc36b0>,
 'Li': <pyscf.gto.mole.Mole at 0x126711a60>,
 'Be': <pyscf.gto.mole.Mole at 0x127a4d8e0>,
 'B': <pyscf.gto.mole.Mole at 0x128604b60>,
 'C': <pyscf.gto.mole.Mole at 0x127b40860>,
 'N': <pyscf.gto.mole.Mole at 0x10d560470>,
 'O': <pyscf.gto.mole.Mole at 0x1286ce030>,
 'F': <pyscf.gto.mole.Mole at 0x128604b00>,
 'H2': <pyscf.gto.mole.Mole at 0x128b03bc0>,
 'HF': <pyscf.gto.mole.Mole at 0x128b00260>,
 'LiH': <pyscf.gto.mole.Mole at 0x128b010a0>,
 'H2O': <pyscf.gto.mole.Mole at 0x128b02210>}

In [4]:
type(mol)

pyscf.gto.mole.Mole

Using `MSTOkG.MSTOOpt.putcoeffs`

In [5]:
iden, basis = getcoeffs(mol)
iden

[['H', 0], ['Li', 0], ['Li', 0], ['Li', 1]]

In [6]:
basis

array([[[1.30975638, 0.4301285 ],
        [0.23313597, 0.67891353]],

       [[6.16384503, 0.4301285 ],
        [1.09716131, 0.67891353]],

       [[0.24591632, 0.04947177],
        [0.06237087, 0.96378241]],

       [[0.24591632, 0.51154071],
        [0.06237087, 0.6128199 ]]])

In [7]:
# changing 0.2331359749 to 0.222222
basis[0][1][0]

np.float64(0.2331359749)

In [8]:
new_basis = basis[:]
new_basis[0][1][0] = 0.222222
new_basis

array([[[1.30975638, 0.4301285 ],
        [0.222222  , 0.67891353]],

       [[6.16384503, 0.4301285 ],
        [1.09716131, 0.67891353]],

       [[0.24591632, 0.04947177],
        [0.06237087, 0.96378241]],

       [[0.24591632, 0.51154071],
        [0.06237087, 0.6128199 ]]])

In [9]:
new_basis_set = putcoeffs(iden, basis)

In [10]:
from copy import deepcopy
mol1 = deepcopy(mol)
mol1.basis = new_basis
mol1.basis

array([[[1.30975638, 0.4301285 ],
        [0.222222  , 0.67891353]],

       [[6.16384503, 0.4301285 ],
        [1.09716131, 0.67891353]],

       [[0.24591632, 0.04947177],
        [0.06237087, 0.96378241]],

       [[0.24591632, 0.51154071],
        [0.06237087, 0.6128199 ]]])

In [11]:
type(new_basis)

numpy.ndarray

In [8]:
getEnergies(mol)

{'HF': np.float64(-7.609810463500129),
 'mol_HF': <pyscf.scf.hf.RHF at 0x128810410>,
 'CISD': np.float64(-7.629059601320522),
 'mol_CISD': <pyscf.ci.cisd.RCISD at 0x127965790>}

In [22]:

element = 'H' # choose your element
mol = moldict('sto-6g')[element] # get the default molecule in your basis
mol.basis

{'H': [[0,
   [35.52322122, 0.00916359628],
   [6.513143725, 0.04936149294],
   [1.822142904, 0.1685383049],
   [0.625955266, 0.3705627997],
   [0.243076747, 0.4164915298],
   [0.100112428, 0.1303340841]]]}

In [23]:
mol1 = BasisReshape(mol, 7)
mol1.basis

{'H': [[0,
   array([3.55232212e+01, 9.16359628e-03]),
   array([6.51314372, 0.04936149]),
   array([1.8221429, 0.1685383]),
   array([0.62595527, 0.3705628 ]),
   array([0.24307675, 0.41649153]),
   array([0.10011243, 0.13033408]),
   array([1., 1.])]]}

In [24]:
mol2 = BasisReshape(mol1, 5)
mol2.basis

{'H': [[0,
   array([3.55232212e+01, 9.16359628e-03]),
   array([6.51314372, 0.04936149]),
   array([1.8221429, 0.1685383]),
   array([0.62595527, 0.3705628 ]),
   array([0.24307675, 0.41649153])]]}